version: '3.8'
services:
  jdk:
    build:
      context: ./jdk
    restart: always
    ports:
      - 8080:8080
    user: spring:spring
    volumes:
      # data
      - "./jdk/data:/home/spring"
    command: /home/spring/mark-down-editor-0.0.1-SNAPSHOT.jar
